//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PdfImageExtractor {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ResTranslate {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResTranslate() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PdfImageExtractor.ResTranslate", typeof(ResTranslate).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add new search item to project.
        /// </summary>
        internal static string Add_new_search_item_to_project {
            get {
                return ResourceManager.GetString("Add new search item to project", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure that you want to overwrite Image File : .
        /// </summary>
        internal static string Are_you_sure_that_you_want_to_overwrite_Image_File___ {
            get {
                return ResourceManager.GetString("Are you sure that you want to overwrite Image File : ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bottom - Center.
        /// </summary>
        internal static string Bottom___Center {
            get {
                return ResourceManager.GetString("Bottom - Center", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bottom - Left.
        /// </summary>
        internal static string Bottom___Left {
            get {
                return ResourceManager.GetString("Bottom - Left", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bottom - Right.
        /// </summary>
        internal static string Bottom___Right {
            get {
                return ResourceManager.GetString("Bottom - Right", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Center.
        /// </summary>
        internal static string Center {
            get {
                return ResourceManager.GetString("Center", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continue activated search?.
        /// </summary>
        internal static string Continue_activated_search_ {
            get {
                return ResourceManager.GetString("Continue activated search?", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not load image .
        /// </summary>
        internal static string Could_not_load_image_ {
            get {
                return ResourceManager.GetString("Could not load image ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Direct search started.
        /// </summary>
        internal static string Direct_search_started {
            get {
                return ResourceManager.GetString("Direct search started", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit 4dots Project.
        /// </summary>
        internal static string Edit_4dots_Project {
            get {
                return ResourceManager.GetString("Edit 4dots Project", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Encrypt PDF.
        /// </summary>
        internal static string Encrypt_PDF {
            get {
                return ResourceManager.GetString("Encrypt PDF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erroneous search 2.
        /// </summary>
        internal static string Erroneous_search_2 {
            get {
                return ResourceManager.GetString("Erroneous search 2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error. Could not send Questionnaire !.
        /// </summary>
        internal static string Error__Could_not_send_Questionnaire__ {
            get {
                return ResourceManager.GetString("Error. Could not send Questionnaire !", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error 1.
        /// </summary>
        internal static string Error_1 {
            get {
                return ResourceManager.GetString("Error 1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error 12.
        /// </summary>
        internal static string Error_12 {
            get {
                return ResourceManager.GetString("Error 12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error 4.
        /// </summary>
        internal static string Error_4 {
            get {
                return ResourceManager.GetString("Error 4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error could not extract image !.
        /// </summary>
        internal static string Error_could_not_extract_image__ {
            get {
                return ResourceManager.GetString("Error could not extract image !", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error could not get options !.
        /// </summary>
        internal static string Error_could_not_get_options__ {
            get {
                return ResourceManager.GetString("Error could not get options !", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error could not parse Arguments !.
        /// </summary>
        internal static string Error_could_not_parse_Arguments__ {
            get {
                return ResourceManager.GetString("Error could not parse Arguments !", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error could not show Preview !.
        /// </summary>
        internal static string Error_could_not_show_Preview__ {
            get {
                return ResourceManager.GetString("Error could not show Preview !", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error during search startup.
        /// </summary>
        internal static string Error_during_search_startup {
            get {
                return ResourceManager.GetString("Error during search startup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extract Images from PDF.
        /// </summary>
        internal static string Extract_Images_from_PDF {
            get {
                return ResourceManager.GetString("Extract Images from PDF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filename of Pdf File.
        /// </summary>
        internal static string Filename_of_Pdf_File {
            get {
                return ResourceManager.GetString("Filename of Pdf File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full Path of Pdf File.
        /// </summary>
        internal static string Full_Path_of_Pdf_File {
            get {
                return ResourceManager.GetString("Full Path of Pdf File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image File Type.
        /// </summary>
        internal static string Image_File_Type {
            get {
                return ResourceManager.GetString("Image File Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import search result.
        /// </summary>
        internal static string Import_search_result {
            get {
                return ResourceManager.GetString("Import search result", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Init Project.
        /// </summary>
        internal static string Init_Project {
            get {
                return ResourceManager.GetString("Init Project", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is From Windows Explorer.
        /// </summary>
        internal static string Is_From_Windows_Explorer {
            get {
                return ResourceManager.GetString("Is From Windows Explorer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MessageTitle.
        /// </summary>
        internal static string MessageTitle {
            get {
                return ResourceManager.GetString("MessageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MessageTitle7.
        /// </summary>
        internal static string MessageTitle7 {
            get {
                return ResourceManager.GetString("MessageTitle7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MessageTitle8.
        /// </summary>
        internal static string MessageTitle8 {
            get {
                return ResourceManager.GetString("MessageTitle8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of Image.
        /// </summary>
        internal static string Number_of_Image {
            get {
                return ResourceManager.GetString("Number of Image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operation Completed Successfully !.
        /// </summary>
        internal static string Operation_Completed_Successfully__ {
            get {
                return ResourceManager.GetString("Operation Completed Successfully !", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operation completed with Errors !.
        /// </summary>
        internal static string Operation_completed_with_Errors__ {
            get {
                return ResourceManager.GetString("Operation completed with Errors !", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page Number.
        /// </summary>
        internal static string Page_Number {
            get {
                return ResourceManager.GetString("Page Number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please add a PDF File first !.
        /// </summary>
        internal static string Please_add_a_PDF_File_first__ {
            get {
                return ResourceManager.GetString("Please add a PDF File first !", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please add only PDF Files !.
        /// </summary>
        internal static string Please_add_only_PDF_Files__ {
            get {
                return ResourceManager.GetString("Please add only PDF Files !", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please add PDF Files first !.
        /// </summary>
        internal static string Please_add_PDF_Files_first__ {
            get {
                return ResourceManager.GetString("Please add PDF Files first !", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please fill out the Questionnaire !.
        /// </summary>
        internal static string Please_fill_out_the_Questionnaire__ {
            get {
                return ResourceManager.GetString("Please fill out the Questionnaire !", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please insert a valid Page Number !.
        /// </summary>
        internal static string Please_insert_a_valid_Page_Number__ {
            get {
                return ResourceManager.GetString("Please insert a valid Page Number !", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please insert an even number !.
        /// </summary>
        internal static string Please_insert_an_even_number__ {
            get {
                return ResourceManager.GetString("Please insert an even number !", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please insert an odd number !.
        /// </summary>
        internal static string Please_insert_an_odd_number__ {
            get {
                return ResourceManager.GetString("Please insert an odd number !", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please insert valid page ranges, comma separated, e.g. 15-20,25-40,50-60.
        /// </summary>
        internal static string Please_insert_valid_page_ranges__comma_separated__e_g__15_20_25_40_50_60 {
            get {
                return ResourceManager.GetString("Please insert valid page ranges, comma separated, e.g. 15-20,25-40,50-60", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preview Picture Set !.
        /// </summary>
        internal static string Preview_Picture_Set__ {
            get {
                return ResourceManager.GetString("Preview Picture Set !", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Replace string process started.
        /// </summary>
        internal static string Replace_string_process_started {
            get {
                return ResourceManager.GetString("Replace string process started", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search duration process.
        /// </summary>
        internal static string Search_duration_process {
            get {
                return ResourceManager.GetString("Search duration process", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Top - Center.
        /// </summary>
        internal static string Top___Center {
            get {
                return ResourceManager.GetString("Top - Center", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Top - Left.
        /// </summary>
        internal static string Top___Left {
            get {
                return ResourceManager.GetString("Top - Left", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Top - Right.
        /// </summary>
        internal static string Top___Right {
            get {
                return ResourceManager.GetString("Top - Right", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to Decrypt Document ! - .
        /// </summary>
        internal static string Unable_to_Decrypt_Document_____ {
            get {
                return ResourceManager.GetString("Unable to Decrypt Document ! - ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uniform process.
        /// </summary>
        internal static string Uniform_process {
            get {
                return ResourceManager.GetString("Uniform process", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unspecified Error.
        /// </summary>
        internal static string Unspecified_Error {
            get {
                return ResourceManager.GetString("Unspecified Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Would you like to add also Subdirectories ?.
        /// </summary>
        internal static string Would_you_like_to_add_also_Subdirectories__ {
            get {
                return ResourceManager.GetString("Would you like to add also Subdirectories ?", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zoom.
        /// </summary>
        internal static string Zoom {
            get {
                return ResourceManager.GetString("Zoom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Αλλαγή Ονόματος.
        /// </summary>
        internal static string Αλλαγή_Ονόματος {
            get {
                return ResourceManager.GetString("Αλλαγή Ονόματος", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Αλλαγή στοιχείων εικόνας.
        /// </summary>
        internal static string Αλλαγή_στοιχείων_εικόνας {
            get {
                return ResourceManager.GetString("Αλλαγή στοιχείων εικόνας", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Αλλαγή Φίλτρου Εικόνας.
        /// </summary>
        internal static string Αλλαγή_Φίλτρου_Εικόνας {
            get {
                return ResourceManager.GetString("Αλλαγή Φίλτρου Εικόνας", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ανανέωση Εικόνας.
        /// </summary>
        internal static string Ανανέωση_Εικόνας {
            get {
                return ResourceManager.GetString("Ανανέωση Εικόνας", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Εισαγωγή Εικόνας.
        /// </summary>
        internal static string Εισαγωγή_Εικόνας {
            get {
                return ResourceManager.GetString("Εισαγωγή Εικόνας", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Εναλλαγή Εικόνας.
        /// </summary>
        internal static string Εναλλαγή_Εικόνας {
            get {
                return ResourceManager.GetString("Εναλλαγή Εικόνας", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Καθορισμός Ονόματος.
        /// </summary>
        internal static string Καθορισμός_Ονόματος {
            get {
                return ResourceManager.GetString("Καθορισμός Ονόματος", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Μορφοποίηση Εικόνας.
        /// </summary>
        internal static string Μορφοποίηση_Εικόνας {
            get {
                return ResourceManager.GetString("Μορφοποίηση Εικόνας", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Νέα Εικόνα.
        /// </summary>
        internal static string Νέα_Εικόνα {
            get {
                return ResourceManager.GetString("Νέα Εικόνα", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Παράμετροι Μετρήσεως Εικόνας.
        /// </summary>
        internal static string Παράμετροι_Μετρήσεως_Εικόνας {
            get {
                return ResourceManager.GetString("Παράμετροι Μετρήσεως Εικόνας", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Περιγραφή Ονόματος.
        /// </summary>
        internal static string Περιγραφή_Ονόματος {
            get {
                return ResourceManager.GetString("Περιγραφή Ονόματος", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Πηγή Εικόνας.
        /// </summary>
        internal static string Πηγή_Εικόνας {
            get {
                return ResourceManager.GetString("Πηγή Εικόνας", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Προβολή Εικόνας 1.
        /// </summary>
        internal static string Προβολή_Εικόνας_1 {
            get {
                return ResourceManager.GetString("Προβολή Εικόνας 1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Προβολή Εικόνων.
        /// </summary>
        internal static string Προβολή_Εικόνων {
            get {
                return ResourceManager.GetString("Προβολή Εικόνων", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Σφάλμα 120.
        /// </summary>
        internal static string Σφάλμα_120 {
            get {
                return ResourceManager.GetString("Σφάλμα 120", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Σφάλμα 1201.
        /// </summary>
        internal static string Σφάλμα_1201 {
            get {
                return ResourceManager.GetString("Σφάλμα 1201", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Υπολογισμός Επιφάνειας.
        /// </summary>
        internal static string Υπολογισμός_Επιφάνειας {
            get {
                return ResourceManager.GetString("Υπολογισμός Επιφάνειας", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Φίλτρο Εικόνας.
        /// </summary>
        internal static string Φίλτρο_Εικόνας {
            get {
                return ResourceManager.GetString("Φίλτρο Εικόνας", resourceCulture);
            }
        }
    }
}
